modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "movelearner"
version = "${project_version}"
displayName = "${project_name} [Cobblemon]"
logoFile ="logo.png"
authors = "Vecoo"
description = "Addon adds system for learn attacks on pokemon."

[[dependencies.movelearner]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.movelearner]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.movelearner]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.movelearner]]
modId = "extralib"
type = "required"
versionRange = "[2.1.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.movelearner]]
modId = "impactor"
type = "optional"
versionRange = "[5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.movelearner]]
modId = "cobbledollars"
type = "optional"
versionRange = "[2.0,)"
ordering = "NONE"
side = "BOTH"